---
- name: Install packages using Chocolatey
  hosts: windows
  vars:
    ansible_shell_type: cmd
  tasks:
    - name: Wait for machine to come online
        wait_for_connection:
          delay: 60
          timeout: 300

    - name: Install pebear
      win_chocolatey:
        name: pebear
        version: '0.6.5.2'
        state: present

    - name: Install ghidra
      win_chocolatey:
        name: ghidra
        version: '10.3.3'
        state: present

    - name: Install dependencywalker
      win_chocolatey:
        name: dependencywalker
        version: '2.2.6000.9'
        state: present

    - name: Download PEview
      win_get_url:
        url: http://wjradburn.com/software/PEview.zip
        dest: C:/PEview.zip

    - name: Unarchive PEview
      win_unzip:
        src: C:/PEview.zip
        dest: C:/PEview
        creates: C:/PEview/PEview.exe
        delete_archive: yes

    - name: Download x64dbg
      win_get_url:
        url: https://sourceforge.net/projects/x64dbg/files/latest/download
        dest: C:/x64dbg.zip
        

    - name: Unarchive x64dbg
      win_unzip:
        src: C:/x64dbg.zip
        dest: C:/x64dbg
        creates: C:/PEview/x64dbg.exe   
        delete_archive: yes   

    - name: Install reshack
      win_chocolatey:
        name: reshack
        version: '5.1.8'
        state: present

    - name: Install procmon
      win_chocolatey:
        name: procmon
        version: '3.95.0'
        state: present
        
    - name: Reboot the machine
      win_reboot:
      when: "'reboot is required' in ansible_playbook_output"  # This condition needs refining based on specific output or other checks.

            